### ISSUE TITLE
陈超英忠诚敬业

### ISSUE THREAD

**Issue by TonTanTin** [nsrce/TheGreatTranslationMovement#10]
![image](https://user-images.githubusercontent.com/66287884/156504069-593f5bf4-6b81-4075-a3cd-4b376783789f.png)

**Comment by TonTanTin** [comment]
Cheng Chao Yin is loyal and has good work ethic, she has dedicated her life to the party (CCP) and her company from the start. She is loyal to the party and her company, she never abandon her tasks and responsibilities. Although her company cannot pay her 20 month of salary, she choose to stay when facing the oppotunity to move to Beijing for another job. She said "my life has been closely bonded with this company, I will not leave it“. 

China Construction Second Engineering Bureau Ltd.

**Comment by nsrce** [comment]
![image](https://user-images.githubusercontent.com/100821325/156506749-635f2d10-0e57-43c3-b412-8e62b3c6b622.png)

**Comment by TonTanTin** [comment]
![New Microsoft PowerPoint Presentation](https://user-images.githubusercontent.com/66287884/156509483-b980e1d6-7086-449e-9a3a-c23ac10aa8e0.jpg)
