### ISSUE TITLE
欢迎光临俄罗斯(Russia)国家馆，请问有什么可以帮您？

### ISSUE THREAD

**Issue by MiaoXingGua** [nsrce/TheGreatTranslationMovement#13]
![](https://cdn.discordapp.com/attachments/948516794476396574/948825719264383016/1DE9980C-555E-43AB-8324-B3041B6063D2.jpg)

**Comment by teikokusyoujyo** [comment]
welcome, how may i help you?

do you have russian sausages?

no

how about some smoothes?

im so sorry but we dont have these as well, everything is out of stock. Please calm down and spend your money rationally.

fuck no we just want to spend all our money buying russian goods!
this shop is owned by the russian government right?

this shop is currently being managed by the russian embassy.

**Comment by kkklienian** [comment]
<img width="841" alt="Screen Shot 2022-03-03 at 4 07 50 PM" src="https://user-images.githubusercontent.com/100822387/156523014-1c818e0f-290f-48de-ab19-ddd72224fadc.png">
