### ISSUE TITLE
他70岁了，大概是最后一次，燃烧自己的全部挽救俄罗斯

### ISSUE THREAD

**Issue by MiaoXingGua** [nsrce/TheGreatTranslationMovement#14]
![](https://media.discordapp.net/attachments/948516794476396574/948817468498002000/2FFA1A7A-B56B-4318-9823-ABC036427CD9.jpg?width=615&height=1331)

**Comment by Carefour** [comment]
Russia use 10 Billion Rouble to buy stock of companies that was hit by sanction

He is 70 years old, maybe is the last time to save Russia. He will make the west afraid of Russia for the next 10 years. He is some Soviet Union but gave his life for Russia, Salute

Strong Russia, I love Putin, this is greatness, selfless, salute to you.

No one oppose Putin as a male god right?

I will use the life of my ex boyfriend to exchange for world peace.

**Comment by o0o20xxo0o** [comment]
1. he's 70, it's probably his last time to sacrifice all of himself to save Russia to make western Europe respect and dare not Russia in the following decade. He was born in the Soviet Union but sacrificed his all to Russia, respect.
2. Kind and powerful Russia, I respect you putin, he is a great and selfless figure. Salute.
3. Putin is OG
4. I agree to let my ex-boyfriend die if it could bring peace to the world

**Comment by o0o20xxo0o** [comment]
笑死了，这个织女有点节目效果

**Comment by Carefour** [comment]
这一个算complete 了吗？

**Comment by nsrce** [comment]
> 这一个算complete 了吗？

图做好才算complete

**Comment by Carefour** [comment]
![Rouble buy stock](https://user-images.githubusercontent.com/100826870/156511828-98e19bde-20d4-4355-8a0a-4394bdf88771.jpg)

**Comment by TonTanTin** [comment]
> ![Rouble buy stock](https://user-images.githubusercontent.com/100826870/156511828-98e19bde-20d4-4355-8a0a-4394bdf88771.jpg)

第一条建议使用@[o0o20xxo0o](https://github.com/o0o20xxo0o) 的翻译
建议把第四条里的male god改成god

**Comment by teikokusyoujyo** [comment]
呃呃 一张破图还翻几遍

**Comment by 3078656247** [comment]
![russiabuysactionedstock_comments_output](https://user-images.githubusercontent.com/100898219/156723641-bdf7826d-d604-4ffa-8d74-ec6db3d553e1.png)
