### ISSUE TITLE
刚才在肯德基点了个香辣鸡腿堡...唱了十五分钟国歌

### ISSUE THREAD

**Issue by zerozaki0752** [nsrce/TheGreatTranslationMovement#19]
![](https://cdn.discordapp.com/attachments/948516794476396574/948836714812674098/IMG_3664.JPG)

**Comment by chonglang3344** [comment]
I just went to KFC to order a Zinger burger, I was told to wait  15 minutes, fuck - 15 minutes for a KFC? 
That's enough time for me to get a casserole porridge, 
I asked for the manager, the server said the manager is not around.
This angered me, fucking foreign companies think they're so fucking awesome? you think you can still continue to bully Chinese people?
So I stood outside the KFC's entrance and sang the Chinese national anthem for 15 minutes.
No one took notice of me so I went home.

**Comment by nsrce** [comment]
![肯德基点了个香辣鸡腿堡 唱了十五分钟国歌 #19](https://user-images.githubusercontent.com/100821325/156888942-11170843-f73d-4a99-819f-cc52c7a2a7cd.png)
