### ISSUE TITLE
夫妻比喻

### ISSUE THREAD

**Issue by nsrce** [nsrce/TheGreatTranslationMovement#2]
![image](https://user-images.githubusercontent.com/100821325/156498027-2e708471-19b3-4ef3-ad0d-2d358301e0df.png)

**Comment by 3078656247** [comment]
原文OCR提取+人工校对:

20多年前，乌克兰与前夫（俄罗斯）离婚，几个孩子也归了她。前夫对她也挺够意思，给她留下了不少家产，之后前夫还替她还清了2000多亿的债务。摆脱了前夫，她开始与村霸（老美）及一帮浪公子（西方）眉来眼去，打情骂俏，直至完全躺在他们的怀里。这倒也罢，她完全听顺村霸的，勾搭在一起对前夫围攻。前夫很生气硬是要回了一孩子：克里米亚。她开始怀恨做梦了，想嫁给北约家族，仗势挤压前夫，而村霸并不想娶她，只想利用她欺负她前夫，她还时不时地对另外两个孩子卢甘斯克、顿涅茨克动不动拳脚相加，逼得这俩孩子哭着找爹，那村长恶霸一直在一旁拱火，只是时不时地送点过期的东西（弹药)。她自以为是有人撑腰，对前夫更加放肆。前夫忍无可忍，并看着俩孩子可怜，带着家伙冲过来把俩孩就要要回去，于是就打起来了......

微博网友发的俄罗斯乌克兰美国等关系解释

换成家庭伦理剧我一下就懂了

**Comment by 3078656247** [comment]
对谷歌翻译友好的中文版本：

20多年前，乌克兰与前夫（俄罗斯）离婚。她获得了几个孩子的抚养权。前夫对她很慷慨，给她留下了不少家产。之后前夫还为她还清了2000多亿的债务。摆脱了前夫，她开始与那村庄恶霸（美国）及一帮浪公子（其他西方国家）调情，直至完全躺在他们的怀里。这倒也罢。但是她完全听从村庄恶霸的。他们勾结在一起对前夫围攻。前夫很生气，硬是要重获一个孩子的抚养权：克里米亚。她开始怀恨在心了。她想嫁给北约家族，仗着他们的势力挤压前夫。然而，村霸并不想娶她，只想利用她欺负她前夫。她还时不时地对另外两个孩子卢甘斯克、顿涅茨克动不动拳脚相加，逼得这俩孩子哭着求助爹。那村庄恶霸一直在一旁对他们挑拨离间。他只是时不时地送点过期的东西（弹药)。她自以为是有人撑腰，对前夫更加放肆。前夫忍无可忍，看在俩孩子可怜的份上，带着武器冲过来要求把俩孩就要要回去，于是就打起来了......

微博网友发的俄罗斯乌克兰美国等关系解释

以家庭伦理剧的角度解释之后，我一下就懂了。

**Comment by 3078656247** [comment]
图片翻译输出 en 版本v0
![Russian invasion from the Family Drama Perspective](https://user-images.githubusercontent.com/100898219/156712829-73aa0f0b-74aa-4b19-8c1e-e397db896502.png)
