### ISSUE TITLE
没有50W彩礼，女朋友被强行拖走，我该怎么办

### ISSUE THREAD

**Issue by zerozaki0752** [nsrce/TheGreatTranslationMovement#20]
![](https://cdn.discordapp.com/attachments/948516794476396574/948835131915907072/IMG_3759.JPG)

**Comment by chonglang3344** [comment]
I didn't have 500k RMB for the bride price, my girlfriend was forcefully taken away, what should I do?

(Bride price is the money a groom pays to the family of the woman, 500k RMB is about 79k USD)

**Comment by nsrce** [comment]
![没有50W彩礼，女朋友被强行拖走，我该怎么办 #20](https://user-images.githubusercontent.com/100821325/156888853-f301a8d3-5d6d-4ec5-abdf-11419d255fb4.png)
