### ISSUE TITLE
我们🇨🇳洗广场屠广场真的无人能敌

### ISSUE THREAD

**Issue by zerozaki0752** [nsrce/TheGreatTranslationMovement#21]
![](https://cdn.discordapp.com/attachments/948516794476396574/948835071706689576/IMG_3762.JPG)

**Comment by o0o20xxo0o** [comment]
丧心病狂

**Comment by o0o20xxo0o** [comment]
LOL, just saw the screenshot of korean square massacre.
our chinese government is unrivaled in squre massacre

deterging the square's dirt laughing my butt off hahaha

**Comment by chonglang3344** [comment]
LOL, I just saw the pictures of the Gwangju Uprising square massacre, Chinese is unrivaled in cleansing and square massacres.

Cleansing square, I'm laughing my butt of hahaha.

**Comment by nsrce** [comment]
![我们cn洗广场屠广场真的无人能敌 #21](https://user-images.githubusercontent.com/100821325/156888824-8d5e4fd0-5c3f-438d-9c05-f5074017ebad.png)
