### ISSUE TITLE
丰县铁链女不得自由，则所有的春天将毫无意义

### ISSUE THREAD

**Issue by zerozaki0752** [nsrce/TheGreatTranslationMovement#22]
![](https://cdn.discordapp.com/attachments/948516794476396574/948828519193018378/48DA95AE-6E07-4B94-9384-31AA3BC62A77.jpg)

**Comment by chonglang3344** [comment]
Context: https://en.wikipedia.org/wiki/Xuzhou_chained_woman_incident
All springtime loses meaning if there is no freedom for the chained women.

**Comment by nsrce** [comment]
![丰县铁链女不得自由，则所有的春天将毫无意义 #22](https://user-images.githubusercontent.com/100821325/156888631-3b470e68-bfcf-4fc3-9b4e-0ebf647b30c5.png)
