### ISSUE TITLE
被蛋壳房东打手催出来...土澳穷国...真不怕我们人民解放军把他们屠了

### ISSUE THREAD

**Issue by zerozaki0752** [nsrce/TheGreatTranslationMovement#23]
![](https://cdn.discordapp.com/attachments/948516794476396574/948853966899392512/IMG_9043.jpg)

**Comment by nsrce** [comment]
> got forced out of my rented apartment by some hitmen hired by the real estate company, got beaten up by the neighorhood securities, i went to the police station but they only filed a case for me and didnt call me back since then, and my fucking boss still didnt pay my check yet, i had no option but to borrow 10 yuan from my high school friend and that motherfucker screenshotted the chat history and harassed me in the school group chat, fuck! why am i so unlucky today! what did i fucking do to deserve this shit
> 
> (cry)
> 
> 下面的
> 
> for a so poor and uncivilized country like Australia how dare they to speak shit to China? Are they really not afraid of our army to swipe out that little place clean?

This is not complete

**Comment by nsrce** [comment]
![被蛋壳房东打手催出来 土澳穷国 真不怕我们人民解放军把他们屠了 #23](https://user-images.githubusercontent.com/100821325/156888954-50971fec-5d66-43ad-b932-3c9ff49eb066.png)
