### ISSUE TITLE
Sanders

### ISSUE THREAD

**Issue by nsrce** [nsrce/TheGreatTranslationMovement#3]
![image](https://user-images.githubusercontent.com/100821325/156498102-0d4d24ee-ca36-4f13-b607-0279c1ad7b3e.png)

**Comment by chonglang3344** [comment]
Context, Sanders says: In the past 200 years, USA is  under the Monroe Doctrine.

Sanders is telling the American Congress, if USA was in Russia's shoes, USA will also invade Ukraine, and will achieve it's goals with whatever means possible, even using nukes, this is not a threat and can very much be a reality.
Biden's government's warmongering can bring USA benefits but it will also bring USA unacceptable consequences.
If USA does not want to fight with Russia then they should quit whilst USA is ahead.
Bernie is reminding the American Congress, that Putin is willing to actually use Nuclear weapons.

Nukes are unlikely, once you use them there is no turning back, however a war is very likely.

**Comment by nsrce** [comment]
![Sanders #3](https://user-images.githubusercontent.com/100821325/156888226-2b6371d5-7d93-4480-9961-ed58fb1dbd5c.png)
