### ISSUE TITLE
去外网装小日本

### ISSUE THREAD

**Issue by Barbalala** [nsrce/TheGreatTranslationMovement#32]
![image](https://user-images.githubusercontent.com/35334743/156710654-85833c4d-5f41-4a41-9528-74e6523e4e06.png)

**Comment by Barbalala** [comment]
Recently there are many dissidents (500k means the rewards by reporting to secret police) that are trying to translate some of our extreme comments to English on foreign social medias. We can do the same, we are going to pretend to be Japanese on the internet, publishing disgusting comments like "seeking Ukrainian female refugees to act in pornography videos" in Japanese, and then translate into English. Let the world see what Japanese really are. But remember, don't use translation programs as it's easy to get caught, it would be best to ask someone good at Japanese to help. EVERYONE, PLEASE REPOST THIS!

**Comment by Barbalala** [comment]
現在スパイがウクライナに関する急進的な意見を英語に翻訳し、外部のインターネットに拡散している。
なぜ我々はそれをすべきではないのか？
私たちは日本人として変装し、国際的に急進的な意見を届けるとこができるからである。
例えばウクライナ人女性をAV女優として働かせ、その後作品をを英訳するなど。
一度外部に拡散すれば世界は日本人がいかに醜い存在であるかを知るだろう。
日本語話者はGoogle翻訳を使う事で我々の真の国民性を暴く事が求められる。

**Comment by o0o20xxo0o** [comment]
<img width="336" alt="2022-03-04 01_03_05-【在线PS软件】在线PS图片（照片）处理工具_在线制作编辑图片ps精简版" src="https://user-images.githubusercontent.com/92959884/156736420-e510a798-a145-41b9-b790-1b1e182a7756.png">

**Comment by o0o20xxo0o** [comment]
<img width="331" alt="2022-03-04 01_28_25-【在线PS软件】在线PS图片（照片）处理工具_在线制作编辑图片ps精简版" src="https://user-images.githubusercontent.com/92959884/156737064-875a5f71-fb79-4126-8e4d-6ca4a2996074.png">

**Comment by o0o20xxo0o** [comment]
<img width="333" alt="2022-03-04 01_36_44-【在线PS软件】在线PS图片（照片）处理工具_在线制作编辑图片ps精简版" src="https://user-images.githubusercontent.com/92959884/156738386-45093c6c-5ca4-4d1a-9491-3fd6a099360b.png">

**Comment by o0o20xxo0o** [comment]
量比质重要
