### ISSUE TITLE
举报同学为乌克兰募捐 获奖1000元

### ISSUE THREAD

**Issue by 3078656247** [nsrce/TheGreatTranslationMovement#33]
![image](https://user-images.githubusercontent.com/100898219/156819561-658c7b23-32b5-4952-8a5e-be648114692c.jpeg)

**Comment by nsrce** [comment]
![丰县铁链女不得自由，则所有的春天将毫无意义 #22](https://user-images.githubusercontent.com/100821325/156888761-ed0143bc-e33d-4602-8071-18fca25c9c57.png)

**Comment by nsrce** [comment]
![举报同学为乌克兰募捐 获奖1000元 #33](https://user-images.githubusercontent.com/100821325/156888767-6c5daedd-8168-4821-b251-254bb89b8f26.png)

**Comment by 3078656247** [comment]
下面是把翻译完的长图拆分为四张：
![IMG_2242](https://user-images.githubusercontent.com/100898219/156912449-64b3b4dc-5cd6-4e6d-83f5-08a2473b3ca8.JPEG)
![IMG_2243](https://user-images.githubusercontent.com/100898219/156912452-b720dade-04cd-42ca-9b3a-bb4c45fe3c23.JPEG)
![IMG_2244](https://user-images.githubusercontent.com/100898219/156912454-88675f0d-9046-4f26-b99e-866e6da5481a.JPEG)
![IMG_2245](https://user-images.githubusercontent.com/100898219/156912457-ccc83652-b83c-41b5-b846-6168e7e2281d.JPEG)

**Comment by chonglang3344** [comment]
改图3
![156912454-88675f0d-9046-4f26-b99e-866e6da5481a](https://user-images.githubusercontent.com/100935706/156930328-9742a320-b45a-445f-a845-93603648397b.png)
