### ISSUE TITLE
马来西亚报纸

### ISSUE THREAD

**Issue by nsrce** [nsrce/TheGreatTranslationMovement#6]
![image](https://user-images.githubusercontent.com/100821325/156499769-2ab582df-7aaa-4d93-976f-fdeaa658996b.png)

**Comment by nsrce** [comment]
![image](https://user-images.githubusercontent.com/100821325/156500926-0a821e72-7ef5-4db4-8bf4-e23fffe8525b.png)

**Comment by TonTanTin** [comment]
Commentator: this war is the most brutal war after WWII, I believe it has shook our heart.
What the Russian-Ukrainian war has taught the world.
Commentator: Don't push a giant into the corner.
