### ISSUE TITLE
外网对线的方法

### ISSUE THREAD

**Issue by nsrce** [nsrce/TheGreatTranslationMovement#7]
![image](https://user-images.githubusercontent.com/100821325/156500391-69cf1894-e9d2-480b-a981-0ce0b1402237.png)

**Comment by chonglang3344** [comment]
Just learnt a new way to counteract/troll the Internet outside of the GFW. Go on Twitter accounts of Indians and British then say "UK is not worthy of the UN Security council permanent seat, Indians are more worthy of this seat." You'll then see a bunch of excited Indians bashing UK and agreeing with you.

Afterwards remember to use Japanese, French or Korean to say Indians are not worthy.

**Comment by nsrce** [comment]
![外网对线的方法 #7](https://user-images.githubusercontent.com/100821325/156888806-6946c588-a4dd-4ceb-ba7b-36aac7a96d69.png)
