### ISSUE TITLE
福利

### ISSUE THREAD

**Issue by nsrce** [nsrce/TheGreatTranslationMovement#8]
![image](https://user-images.githubusercontent.com/100821325/156501900-144a0c99-4094-4be5-a83e-d73f137e2059.png)

**Comment by TonTanTin** [comment]
Give me an example of any social benifits the west have that China don't, I bet you can't. This is the power of knowledge, and where does knowledge come from? just search it on Baidu (Chinese Google).

**Comment by kkklienian** [comment]
<img width="365" alt="Screen Shot 2022-03-03 at 1 43 34 PM" src="https://user-images.githubusercontent.com/100822387/156503756-82770c69-f270-408b-93a6-8ffcb0a42223.png">
