### ISSUE TITLE
美国还钱美国老赖

### ISSUE THREAD

**Issue by o0o20xxo0o** [nsrce/TheGreatTranslationMovement#9]
![IMG_1325](https://user-images.githubusercontent.com/92959884/156502420-abd3617e-491c-462a-9528-2020139477e0.png)
![IMG_1326](https://user-images.githubusercontent.com/92959884/156502435-9981c82e-5326-46a7-a60e-bf8ee91f162a.png)
![IMG_1327](https://user-images.githubusercontent.com/92959884/156502442-e96aea14-a3e6-4f80-aa2e-1cbe906d0a77.png)

**Comment by chonglang3344** [comment]
News article: 
Chinese UN ambassador reminds USA that "repaying your debt is not generosity but a fundamental obligation." In regards to Biden signing executive order to unfreeze Afghan central bank funds and take half of that as compensation for 9.11 victims.

(Up voted 200.4k times)

Comments:
Terrorists (USA) sure knows how to rob money

Repay (the Afghans) now!

Americans became the "world's richest country" by robbing other people's wealth.

**Comment by chonglang3344** [comment]
Comments:
America never intended to repay their debt to us (China) ? they're playing ticks

America is the world's biggest deadbeat.

America has no sense of shame, they're coveting for Afghanistan's money, repaying your debt is a fundamental obligation!

Repaying your debt is a fundamental obligation.

Taking other's compensation to line on own pockets right. Way to go looking high and mighty.

**Comment by nsrce** [comment]
![没有50W彩礼，女朋友被强行拖走，我该怎么办 #20](https://user-images.githubusercontent.com/100821325/156888896-bc2cf41b-8aa5-40c8-bd56-bbbdd69673f5.png)
![美国还钱美国老赖 #9](https://user-images.githubusercontent.com/100821325/156888902-3f61d17f-bdb1-48c6-be5a-e922817f3df6.png)
